create database StudentDB;
use StudentDB;
create table Students(Studentid int not null,Fisrtname varchar(50) not null,Lastname varchar(50) not null,DOB date not null,Gender char(1) not null,Major varchar (100) not null,primary key(Studentid));
insert into Students values(1,'John','Doe','2000-01-15','M','Computer Science'),(2,'Jane','Smith','1999-8-25','F','Electrical Engineering');
select *from Students where Major='Computer Science';
update Students set Major='Information Technology' where Studentid=1;
delete from Students where Studentid=2;
alter table Students add Email varchar(100) not null;
alter table Students change column Fisrtname Firstname varchar(50) not null;
select * from Students;
select Firstname,Lastname,Major from Students where DOB >'2000-01-01';
select Firstname,Major from Students;
update Students set Email='siansarjith@gmail.com' where Studentid=1;
insert into Students values(2,'Sian','Julian','2000-02-14','M','Computer Science','zoro@gmail.com'),(3,'Siya','Julian','2000-05-14','F','Computer Science','siya@gmail.com'),(4,'Avin','Anil','2000-02-19','M','Information Technology','avin@gmail.com'),(5,'Nandu','Ganesh','2000-02-14','M','Mechanical Engineering','nandu@gmail.com'),(6,'Anvi','praveen','2000-02-10','M','Computer Science','anvi@gmail.com');
select *from Students;